unit projeto.model.dao.consts;

interface

const

  _COND_CLIENTE = ' WHERE CODCLIENTE = %d';
  _SEL_CLIENTE = 'SELECT CODCLIENTE, NOME, CIDADE, UF FROM CLIENTE';

  _COND_PRODUTO = ' WHERE CODPRODUTO = %d';
  _SEL_PRODUTO = 'SELECT CODPRODUTO, DESPRODUTO, VLRVENDA FROM PRODUTO';

  _DEL_PEDIDO = 'DELETE FROM PEDIDO WHERE NROPEDIDO = %d ';
  _DEL_PEDIDO_ITENS = 'DELETE FROM PEDIDOITENS WHERE NROPEDIDO = %d ';

  _UPD_PEDIDO_ITENS = 'UPDATE PEDIDOITENS SET QUANTIDADE = %d, VLRUNITARIO = %d, VLRTOTAL = %d WHERE NROPEDIDOITENS = %d ';

  _COND_PEDIDO = ' WHERE NROPEDIDO = %d';
  _SEL_PEDIDO = 'SELECT PEDIDO.NROPEDIDO, PEDIDO.CODCLIENTE, PEDIDO.DATEMISSAO, PEDIDO.VLRTOTAL, CLIENTE.NOME ' +
                '  FROM PEDIDO ' +
                ' INNER JOIN CLIENTE ON CLIENTE.CODCLIENTE=PEDIDO.CODCLIENTE';

  _COND_PEDIDO_ITENS = ' WHERE PEDIDOITENS.NROPEDIDO = %d';
  _SEL_PEDIDO_ITENS = 'SELECT PEDIDOITENS.NROPEDIDO, ' +
                      '       PEDIDOITENS.NROPEDIDOITENS, ' +
                      '       PEDIDOITENS.CODPRODUTO, ' +
                      '       PEDIDOITENS.QUANTIDADE, ' +
                      '       PEDIDOITENS.VLRUNITARIO, ' +
                      '       PEDIDOITENS.VLRTOTAL, ' +
                      '       PRODUTO.DESPRODUTO ' +
                      '  FROM PEDIDOITENS ' +
                      ' INNER JOIN PRODUTO ON (PEDIDOITENS.CODPRODUTO=PRODUTO.CODPRODUTO) ';

  _INS_PEDIDO = 'INSERT INTO PEDIDO (CODCLIENTE,VLRTOTAL) VALUES (%d,%s) ';

  _SEL_MAX = 'SELECT MAX(NROPEDIDO) NROPEDIDO FROM PEDIDO';

  _INS_PEDIDOITENS = 'INSERT INTO PEDIDOITENS (NROPEDIDO,CODPRODUTO,QUANTIDADE,VLRUNITARIO,VLRTOTAL) VALUES (%d,%d,%d,%s,%s)';

implementation

end.
